

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'DailyTasksLogs' AND TABLE_SCHEMA = 'dbo' AND COLUMN_NAME = 'Colour')
BEGIN
	ALTER TABLE dbo.DailyTasksLogs Add Colour INT DEFAULT(0)  -- 0: Normal, 1:Warning, 2:Danger
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'DailyTasksLogs' AND TABLE_SCHEMA = 'dbo' AND COLUMN_NAME = 'LogType')
BEGIN
	ALTER TABLE dbo.DailyTasksLogs Add LogType INT DEFAULT(0)
END
GO