
SELECT * FROM Projects WITH(NOLOCK) 
SELECT * FROM Users WITH(NOLOCK)
SELECt * FROM Roles WITH(NOLOCK)
SELECt * FROM UserRoles WITH(NOLOCK)
SELECT * FROM PasswordResets WITH(NOLOCK)
SELECT * FROM ResourceNames WITH(NOLOCK)
SELECT * FROM DropDownValues WITH(NOLOCK)

SELECT * FROM DailyTasks WITH(NOLOCK)
SELECT * FROM SubTasks WITH(NOLOCK)
SELECT * FROM SubTaskWorkEntrys WITH(NOLOCK)

SELECT * FROM DailyTasksLogs WITH(NOLOCK)

SELECT * FROM UseFullLinks WITH(NOLOCK)

SELECT * FROM TaskComments WITH(NOLOCK)

SELECT * FROM RNAndFeatureList WITH(NOLOCK)

