// <auto-generated />
using System;
using ARAS.Infrastructure.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ARAS.Infrastructure.Migrations
{
    [DbContext(typeof(ARASDbContext))]
    [Migration("20251125055624_FirstByRKS")]
    partial class FirstByRKS
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ARAS.Infrastructure.DBModels.YourApp.DomainModels.DailyTask", b =>
                {
                    b.Property<long>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TaskId"));

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Catagory")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EHrsToday")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAlive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsApprove")
                        .HasColumnType("bit");

                    b.Property<bool>("ItemToDiscuss")
                        .HasColumnType("bit");

                    b.Property<string>("Jira")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ManagerComments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MyComments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Network")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("ProjectKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SubProject")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TaskSeq")
                        .HasColumnType("int");

                    b.Property<Guid>("TaskUniqueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("TodayDayWork")
                        .HasColumnType("bit");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TaskId");

                    b.ToTable("DailyTasks");
                });

            modelBuilder.Entity("ARAS.Infrastructure.DBModels.YourApp.DomainModels.DailyTasksLog", b =>
                {
                    b.Property<long>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LogId"));

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Log")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("LogId");

                    b.ToTable("DailyTasksLogs");
                });

            modelBuilder.Entity("ARAS.Infrastructure.DBModels.YourApp.DomainModels.DropDownValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("GuidId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProjectKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("DropDownValues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GuidId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ProjectKey = "cpp",
                            Type = "project",
                            Value = "CPP"
                        },
                        new
                        {
                            Id = 2,
                            GuidId = new Guid("22222222-2222-2222-2222-222222222222"),
                            ProjectKey = "cpp",
                            Type = "project",
                            Value = "PPG"
                        },
                        new
                        {
                            Id = 3,
                            GuidId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ProjectKey = "cpp",
                            Type = "project",
                            Value = "TC"
                        },
                        new
                        {
                            Id = 4,
                            GuidId = new Guid("44444444-4444-4444-4444-444444444444"),
                            ProjectKey = "ccp",
                            Type = "project",
                            Value = "CCP"
                        },
                        new
                        {
                            Id = 5,
                            GuidId = new Guid("55555555-5555-5555-5555-555555555555"),
                            ProjectKey = "plat",
                            Type = "project",
                            Value = "PLAT"
                        },
                        new
                        {
                            Id = 6,
                            GuidId = new Guid("66666666-6666-6666-6666-666666666666"),
                            ProjectKey = "cpp",
                            Type = "network",
                            Value = "MDS"
                        },
                        new
                        {
                            Id = 7,
                            GuidId = new Guid("77777777-7777-7777-7777-777777777777"),
                            ProjectKey = "cpp",
                            Type = "network",
                            Value = "Visa"
                        },
                        new
                        {
                            Id = 8,
                            GuidId = new Guid("88888888-8888-8888-8888-888888888888"),
                            ProjectKey = "cpp",
                            Type = "network",
                            Value = "Pulse_ED"
                        },
                        new
                        {
                            Id = 9,
                            GuidId = new Guid("99999999-9999-9999-9999-999999999999"),
                            ProjectKey = "cpp",
                            Type = "network",
                            Value = "Star"
                        },
                        new
                        {
                            Id = 10,
                            GuidId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            ProjectKey = "cpp",
                            Type = "network",
                            Value = "Discover"
                        },
                        new
                        {
                            Id = 11,
                            GuidId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            ProjectKey = "cpp",
                            Type = "network",
                            Value = "IPM"
                        },
                        new
                        {
                            Id = 12,
                            GuidId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            ProjectKey = "cpp",
                            Type = "network",
                            Value = "RupaySms"
                        },
                        new
                        {
                            Id = 13,
                            GuidId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            ProjectKey = "cpp",
                            Type = "network",
                            Value = "RupayDms"
                        },
                        new
                        {
                            Id = 14,
                            GuidId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            ProjectKey = "cpp",
                            Type = "network",
                            Value = "Jaywan"
                        },
                        new
                        {
                            Id = 15,
                            GuidId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            ProjectKey = "ccp",
                            Type = "network",
                            Value = "VisaSms"
                        },
                        new
                        {
                            Id = 16,
                            GuidId = new Guid("12121212-1212-1212-1212-121212121212"),
                            ProjectKey = "ccp",
                            Type = "network",
                            Value = "VisaDms"
                        },
                        new
                        {
                            Id = 17,
                            GuidId = new Guid("13131313-1313-1313-1313-131313131313"),
                            ProjectKey = "ccp",
                            Type = "network",
                            Value = "IPM"
                        },
                        new
                        {
                            Id = 18,
                            GuidId = new Guid("14141414-1414-1414-1414-141414141414"),
                            ProjectKey = "ccp",
                            Type = "network",
                            Value = "AmexDef"
                        },
                        new
                        {
                            Id = 19,
                            GuidId = new Guid("15151515-1515-1515-1515-151515151515"),
                            ProjectKey = "ccp",
                            Type = "network",
                            Value = "AmexAch"
                        },
                        new
                        {
                            Id = 20,
                            GuidId = new Guid("16161616-1616-1616-1616-161616161616"),
                            ProjectKey = "ccp",
                            Type = "network",
                            Value = "Discover"
                        },
                        new
                        {
                            Id = 21,
                            GuidId = new Guid("17171717-1717-1717-1717-171717171717"),
                            ProjectKey = "ccp",
                            Type = "network",
                            Value = "RupaySms"
                        },
                        new
                        {
                            Id = 22,
                            GuidId = new Guid("18181818-1818-1818-1818-181818181818"),
                            ProjectKey = "ccp",
                            Type = "network",
                            Value = "RupayDms"
                        },
                        new
                        {
                            Id = 23,
                            GuidId = new Guid("19191919-1919-1919-1919-191919191919"),
                            ProjectKey = "plat",
                            Type = "network",
                            Value = "IPM"
                        },
                        new
                        {
                            Id = 24,
                            GuidId = new Guid("20202020-2020-2020-2020-202020202020"),
                            ProjectKey = "plat",
                            Type = "category",
                            Value = "Internal"
                        },
                        new
                        {
                            Id = 25,
                            GuidId = new Guid("21212121-2121-2121-2121-212121212121"),
                            ProjectKey = "cpp",
                            Type = "category",
                            Value = "Internal"
                        },
                        new
                        {
                            Id = 26,
                            GuidId = new Guid("22222222-2222-2222-2222-212121212121"),
                            ProjectKey = "ccp",
                            Type = "category",
                            Value = "Internal"
                        },
                        new
                        {
                            Id = 27,
                            GuidId = new Guid("23232323-2323-2323-2323-232323232323"),
                            ProjectKey = "ccp",
                            Type = "category",
                            Value = "Prod"
                        },
                        new
                        {
                            Id = 28,
                            GuidId = new Guid("24242424-2424-2424-2424-242424242424"),
                            ProjectKey = "cpp",
                            Type = "category",
                            Value = "Prod"
                        },
                        new
                        {
                            Id = 29,
                            GuidId = new Guid("25252525-2525-2525-2525-252525252525"),
                            ProjectKey = "plat",
                            Type = "category",
                            Value = "Prod"
                        },
                        new
                        {
                            Id = 30,
                            GuidId = new Guid("26262626-2626-2626-2626-262626262626"),
                            ProjectKey = "plat",
                            Type = "category",
                            Value = "Regular"
                        },
                        new
                        {
                            Id = 31,
                            GuidId = new Guid("27272727-2727-2727-2727-272727272727"),
                            ProjectKey = "cpp",
                            Type = "category",
                            Value = "Regular"
                        },
                        new
                        {
                            Id = 32,
                            GuidId = new Guid("28282828-2828-2828-2828-282828282828"),
                            ProjectKey = "ccp",
                            Type = "category",
                            Value = "Regular"
                        },
                        new
                        {
                            Id = 33,
                            GuidId = new Guid("29292929-2929-2929-2929-292929292929"),
                            ProjectKey = "cpp",
                            Type = "status",
                            Value = "Pending"
                        },
                        new
                        {
                            Id = 34,
                            GuidId = new Guid("30303030-3030-3030-3030-303030303030"),
                            ProjectKey = "cpp",
                            Type = "status",
                            Value = "In-Progress"
                        },
                        new
                        {
                            Id = 35,
                            GuidId = new Guid("31313131-3131-3131-3131-313131313131"),
                            ProjectKey = "cpp",
                            Type = "status",
                            Value = "Done"
                        },
                        new
                        {
                            Id = 36,
                            GuidId = new Guid("32323232-3232-3232-3232-323232323232"),
                            ProjectKey = "cpp",
                            Type = "status",
                            Value = "On-Hold"
                        },
                        new
                        {
                            Id = 37,
                            GuidId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ProjectKey = "cpp",
                            Type = "status",
                            Value = "Follow-Up"
                        },
                        new
                        {
                            Id = 38,
                            GuidId = new Guid("34343434-3434-3434-3434-343434343434"),
                            ProjectKey = "ccp",
                            Type = "status",
                            Value = "Pending"
                        },
                        new
                        {
                            Id = 39,
                            GuidId = new Guid("35353535-3535-3535-3535-353535353535"),
                            ProjectKey = "ccp",
                            Type = "status",
                            Value = "In-Progress"
                        },
                        new
                        {
                            Id = 40,
                            GuidId = new Guid("36363636-3636-3636-3636-363636363636"),
                            ProjectKey = "ccp",
                            Type = "status",
                            Value = "Done"
                        },
                        new
                        {
                            Id = 41,
                            GuidId = new Guid("37373737-3737-3737-3737-373737373737"),
                            ProjectKey = "ccp",
                            Type = "status",
                            Value = "On-Hold"
                        },
                        new
                        {
                            Id = 42,
                            GuidId = new Guid("38383838-3838-3838-3838-383838383838"),
                            ProjectKey = "ccp",
                            Type = "status",
                            Value = "Follow-Up"
                        },
                        new
                        {
                            Id = 43,
                            GuidId = new Guid("39393939-3939-3939-3939-393939393939"),
                            ProjectKey = "plat",
                            Type = "status",
                            Value = "Pending"
                        },
                        new
                        {
                            Id = 44,
                            GuidId = new Guid("40404040-4040-4040-4040-404040404040"),
                            ProjectKey = "plat",
                            Type = "status",
                            Value = "In-Progress"
                        },
                        new
                        {
                            Id = 45,
                            GuidId = new Guid("41414141-4141-4141-4141-414141414141"),
                            ProjectKey = "plat",
                            Type = "status",
                            Value = "Done"
                        },
                        new
                        {
                            Id = 46,
                            GuidId = new Guid("42424242-4242-4242-4242-424242424242"),
                            ProjectKey = "plat",
                            Type = "status",
                            Value = "On-Hold"
                        },
                        new
                        {
                            Id = 47,
                            GuidId = new Guid("43434343-4343-4343-4343-434343434343"),
                            ProjectKey = "plat",
                            Type = "status",
                            Value = "Follow-Up"
                        });
                });

            modelBuilder.Entity("ARAS.Infrastructure.DBModels.YourApp.DomainModels.PasswordReset", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(225)
                        .HasColumnType("nvarchar(225)");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("int");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<int>("OTP")
                        .HasColumnType("int");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("ValidityDateTime")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("PasswordResets");
                });

            modelBuilder.Entity("ARAS.Infrastructure.DBModels.YourApp.DomainModels.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectId"), 5001L);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ProjectKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ProjectId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            ProjectId = 5001,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Have networks - MDS, Visa Sms, Pulse EDF, Star, IPM, Discover, Rupay Sms & Dms, Jaywan",
                            ProjectKey = "cpp",
                            ProjectName = "Core Prepaid Processing"
                        },
                        new
                        {
                            ProjectId = 5002,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Have networks - Visa Sms, Amex, IPM, Discover, Rupay Sms & Dms, Jaywan",
                            ProjectKey = "ccp",
                            ProjectName = "Core Credit Processing"
                        },
                        new
                        {
                            ProjectId = 5003,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Have network - Only Mastercard IPM",
                            ProjectKey = "plat",
                            ProjectName = "Plat Processing"
                        });
                });

            modelBuilder.Entity("ARAS.Infrastructure.DBModels.YourApp.DomainModels.ResourceName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("AddedByUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("GuidId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsShow")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ResourceNames");
                });

            modelBuilder.Entity("ARAS.Infrastructure.DBModels.YourApp.DomainModels.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"), 101L);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsSystemRole")
                        .HasColumnType("bit");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 101,
                            Description = "",
                            IsSystemRole = false,
                            RoleName = "admin"
                        },
                        new
                        {
                            RoleId = 102,
                            Description = "",
                            IsSystemRole = false,
                            RoleName = "manager"
                        },
                        new
                        {
                            RoleId = 103,
                            Description = "",
                            IsSystemRole = false,
                            RoleName = "lead"
                        },
                        new
                        {
                            RoleId = 104,
                            Description = "",
                            IsSystemRole = false,
                            RoleName = "resource"
                        });
                });

            modelBuilder.Entity("ARAS.Infrastructure.DBModels.YourApp.DomainModels.SubTask", b =>
                {
                    b.Property<long>("SubTaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SubTaskId"));

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsApprove")
                        .HasColumnType("bit");

                    b.Property<bool>("IsColour")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSelf")
                        .HasColumnType("bit");

                    b.Property<string>("Remark")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("SubTaskETA")
                        .HasPrecision(5, 1)
                        .HasColumnType("decimal(5,1)");

                    b.Property<string>("SubTaskName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubTaskSeq")
                        .HasColumnType("int");

                    b.Property<Guid>("SubTaskUniqueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TaskUniqueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("SubTaskId");

                    b.ToTable("SubTasks");
                });

            modelBuilder.Entity("ARAS.Infrastructure.DBModels.YourApp.DomainModels.SubTaskWorkEntry", b =>
                {
                    b.Property<long>("WorkEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("WorkEntryId"));

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateOnly>("EntryDate")
                        .HasColumnType("date");

                    b.Property<decimal>("EntryHrs")
                        .HasPrecision(5, 1)
                        .HasColumnType("decimal(5,1)");

                    b.Property<Guid>("SubTaskUniqueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TaskUniqueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("WorkEntryUniqueId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("WorkEntryId");

                    b.ToTable("SubTaskWorkEntrys");
                });

            modelBuilder.Entity("ARAS.Infrastructure.DBModels.YourApp.DomainModels.TaskComment", b =>
                {
                    b.Property<Guid>("GuidId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("CommentEditedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentId"));

                    b.Property<DateTimeOffset>("CommentedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPreviouslyEdited")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProjectKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TaskUniqueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("GuidId");

                    b.ToTable("TaskComments");
                });

            modelBuilder.Entity("ARAS.Infrastructure.DBModels.YourApp.DomainModels.UseFullLink", b =>
                {
                    b.Property<Guid>("GuidId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LinkName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GuidId");

                    b.ToTable("UseFullLinks");
                });

            modelBuilder.Entity("ARAS.Infrastructure.DBModels.YourApp.DomainModels.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserId"), 1001L);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(225)
                        .HasColumnType("nvarchar(225)");

                    b.Property<long>("EmployeeNumber")
                        .HasColumnType("bigint");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1001L,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "admin",
                            EmployeeNumber = 0L,
                            FailedLoginCount = 0,
                            FirstName = "Admin",
                            IsActive = true,
                            IsEmailConfirmed = true,
                            LastName = "Admin",
                            Metadata = "",
                            MiddleName = "",
                            PasswordHash = "jjVzvvxb4B1w2/P8vByljzlH3CsIgBYLGEbfP7MWBdw=",
                            PasswordSalt = "RW6uOLKZH7GrVfzOeNtDjA==",
                            UserGuid = new Guid("683869d4-10af-4a94-a520-0bf2470d28a6"),
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("ARAS.Infrastructure.DBModels.YourApp.DomainModels.UserRole", b =>
                {
                    b.Property<long>("UserRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserRoleId"), 801L);

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("UserRoleId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserRoleId = 801L,
                            AssignedAt = new DateTimeOffset(new DateTime(2025, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ProjectId = 5001,
                            RoleId = 101,
                            UserId = 1001L
                        },
                        new
                        {
                            UserRoleId = 802L,
                            AssignedAt = new DateTimeOffset(new DateTime(2025, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ProjectId = 5002,
                            RoleId = 101,
                            UserId = 1001L
                        },
                        new
                        {
                            UserRoleId = 803L,
                            AssignedAt = new DateTimeOffset(new DateTime(2025, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ProjectId = 5003,
                            RoleId = 101,
                            UserId = 1001L
                        });
                });

            modelBuilder.Entity("ARAS.Infrastructure.DBModels.YourApp.DomainModels.UserRole", b =>
                {
                    b.HasOne("ARAS.Infrastructure.DBModels.YourApp.DomainModels.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ARAS.Infrastructure.DBModels.YourApp.DomainModels.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ARAS.Infrastructure.DBModels.YourApp.DomainModels.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Role");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
